Switch to protobuf3
TeXitoi/osmpbfreader-rs pull request #50
Opened 2024-12-19 19:26 UTC by Tristramg

I also fixed some minor clippy warnings. If you prefer that I do a separate pull request, just tell me!

2024-12-19 19:39 UTC, TeXitoi requested changes
Great work, thanks!

Only a minor stylish remark.

2024-12-19 19:39 UTC, TeXitoi commented on src/groups.rs
>                      }
```suggestion
                    t.enum_value().map(|t| Ref {
                        member: match t {
                            NODE => NodeId(m).into(),
                            WAY => WayId(m).into(),
                            RELATION => RelationId(m).into(),
                        },
                        role: make_string(role as usize, self.block),
                    })
```

2024-12-19 20:22 UTC, Tristramg commented
Thank you for the quick review.
I rebased on the right remote and applied your suggestion

2024-12-20 09:18 UTC, merged

2024-12-20 09:21 UTC, TeXitoi commented
v0.17.0 published, thanks!

2024-12-20 09:34 UTC, TeXitoi commented
10 years of osmpbfreader!